#
# Copyright 2011 Nathan Fiedler. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.
#

include $(GOROOT)/src/Make.inc

TARG=swatcl
GOFILES=\
	commands.go\
	errors.go\
	eval.go\
	expr.go\
	interpreter.go\
	lexer.go\
	operator.go\

include $(GOROOT)/src/Make.pkg
